### ISSUE TITLE
Enable skype calls

### ISSUE THREAD

**Issue by adlk** [meetfranz/recipe-skype#1]
It should be possible to enable skype calls by overriding the user agent.

**Comment by BAndonovski** [comment]
I don't know how helpful this would be, but there already are open source solutions that enable Skype calls inside electron apps; maybe it's worth having a look at them for inspiration?

**Comment by adlk** [comment]
The fix was deployed.

**Comment by BAndonovski** [comment]
Just updated to 5.1.0-beta.1, the button is still disabled.
