### ISSUE TITLE
Attachment says "This page isn’t working" after opening in default Chrome

### ISSUE THREAD

**Issue by austinhuang0131** [meetfranz/recipe-skype#10]
= I can't open attachments.

**Comment by austinhuang0131** [comment]
Okay, the problem itself is my Chrome's problem...But is it possible to open attachments as a new window inside the Franz app?

**Comment by feldmarv** [comment]
We run into the same issue. All shared images cannot be opened. Is there any solution for this?

**Comment by austinhuang0131** [comment]
Oh wait it's in #2
