### ISSUE TITLE
Skype web has a new URL and new design with it

### ISSUE THREAD

**Issue by omergulen** [meetfranz/recipe-skype#15]
I just found out that every time I open the Franz and use Skype(https://web.skype.com) there is a notification on the top which encourages me to click and see the new version of the web Skype.

http://prntscr.com/lpure0

So, I tried it out and saw that is very cool, it's like the desktop app, faster and smoother.
I think we should change the service URL of Skype to the new one.

**Comment by closingin** [comment]
Hello Ömer,

I added a comment on a similar issue (#22), maybe you can close this issue and follow there ? :slightly_smiling_face:
