### ISSUE TITLE
Browser not supported

### ISSUE THREAD

**Issue by daniellukaszgmailcom** [meetfranz/recipe-skype#24]
I use Linux and Franz 5.0.0-beta.15. I have the warning from the attachment on the Skype service tab. Unfortunately Skype is no longer usable.
![Zaznaczenie_002](https://user-images.githubusercontent.com/29166713/54767398-59fbe400-4bfd-11e9-8ca5-5e340d4e56a3.png)

Thanks for your product and support! ;)

**Comment by daniellukaszgmailcom** [comment]
the same solution works for skype: https://github.com/meetfranz/franz/issues/1347

**Comment by morgej** [comment]
> the same solution works for skype: https://github.com/meetfranz/franz/issues/1347

The link to the Franz issue is showing a 404 - any idea what the fix for this was?
