### ISSUE TITLE
Skype appears in the wrong language

### ISSUE THREAD

**Issue by gonzalorodrigo** [meetfranz/recipe-skype#3]
- Version: Franz 5.0.0-beta.10.7
- OS: macOS SIerra 10.12.6
- System Language: Spanish
- Language in which Skype loads: Arab

Summary:
I just installed Beta 5 migrating from standard Franz. I had to re-add the services. When I added Skype, it appears in Arab. I have not tried to log-in, because the text box is in "writing from right to left" mode and it's hard to type.

Attached Image:
![captura de pantalla 2017-10-19 a la s 09 18 55](https://user-images.githubusercontent.com/12073983/31786456-67cd40ac-b4bd-11e7-9f78-8bf3d8694a40.png)

**Comment by gonzalorodrigo** [comment]
HI, after a recipe update, it appears in the right language.

**Comment by dcazarez** [comment]
How did you do that?
